=begin
#SARD API

#This is the SARD API. For more information visit <a href=\"https://www.sardjv.co.uk\">www.sardjv.co.uk</a>.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CouncilMembershipApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CouncilMembershipApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CouncilMembershipApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CouncilMembershipApi' do
    it 'should create an instance of CouncilMembershipApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CouncilMembershipApi)
    end
  end

  # unit tests for api_v1_council_memberships_get
  # council memberships index
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page 
  # @option opts [String] :per_page 
  # @option opts [String] :filter_user_id 
  # @return [CouncilMembershipsResponse]
  describe 'api_v1_council_memberships_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_council_memberships_id_get
  # show council membership
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [CouncilMembershipResponse]
  describe 'api_v1_council_memberships_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_council_memberships_id_patch
  # update council membership
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [CouncilMembershipPatchParams] :council_membership 
  # @return [CouncilMembershipPatchParams]
  describe 'api_v1_council_memberships_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_council_memberships_post
  # create council membership
  # @param [Hash] opts the optional parameters
  # @option opts [CouncilMembershipPostParams] :council_membership 
  # @return [CouncilMembershipPostParams]
  describe 'api_v1_council_memberships_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
