=begin
#SARD API

#This is the SARD API. For more information visit <a href=\"https://www.sardjv.co.uk\">www.sardjv.co.uk</a>.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::EleaveCalendarApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EleaveCalendarApi' do
  before do
    # run before each test
    @instance = SwaggerClient::EleaveCalendarApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EleaveCalendarApi' do
    it 'should create an instance of EleaveCalendarApi' do
      expect(@instance).to be_instance_of(SwaggerClient::EleaveCalendarApi)
    end
  end

  # unit tests for api_v1_eleave_calendars_get
  # eleave calendars index
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page 
  # @option opts [String] :per_page 
  # @option opts [String] :filter_id 
  # @option opts [String] :filter_owner_id 
  # @option opts [String] :filter_approver_ids 
  # @return [EleaveCalendarsResponse]
  describe 'api_v1_eleave_calendars_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_eleave_calendars_id_get
  # show eleave calendar
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [EleaveCalendarResponse]
  describe 'api_v1_eleave_calendars_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_eleave_calendars_id_patch
  # update eleave calendar
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [EleaveCalendarPatchParams] :eleave_calendar 
  # @return [EleaveCalendarPatchParams]
  describe 'api_v1_eleave_calendars_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_eleave_calendars_post
  # create eleave calendar
  # @param [Hash] opts the optional parameters
  # @option opts [EleaveCalendarPostParams] :eleave_calendar 
  # @return [EleaveCalendarPostParams]
  describe 'api_v1_eleave_calendars_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
