=begin
#SARD API

#This is the SARD API. For more information visit <a href=\"https://www.sardjv.co.uk\">www.sardjv.co.uk</a>.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TenantsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TenantsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TenantsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TenantsApi' do
    it 'should create an instance of TenantsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::TenantsApi)
    end
  end

  # unit tests for api_v1_tenants_get
  # tenants index
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page 
  # @option opts [String] :per_page 
  # @option opts [String] :filter_pilot 
  # @option opts [String] :filter_name 
  # @return [TenantsResponse]
  describe 'api_v1_tenants_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_tenants_id_get
  # show tenant
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [TenantResponse]
  describe 'api_v1_tenants_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
